apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - alertmanager
  - grafana
  - kube-state-metrics
  - loki
  - node-exporter
  - prometheus
  - promtail
  - goldilocks
